version: '3'

services:
  qbittorrentvpn:
    restart: always
    image: oxidand/qbittorrentvpn
    container_name: qbittorrentvpn
    environment:
      - VPN_ENABLED=yes
      - NAME_SERVERS=1.1.1.1,1.0.0.1
      - LAN_NETWORK=192.168.1.0/24
      - PUID=$UID
      - PGID=$GID
      - UMASK=002
    ports:
      - 8080:8080
    volumes:
      - ${DATA_PATH}/qBittorrent/:/config/
      - ${DOWNLOADS_PATH}/:/downloads/
      - /etc/localtime:/etc/localtime:ro
    privileged: true
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
  
  jackett:
    restart: always
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=$UID
      - PGID=$GID
    ports:
      - 9117:9117
    volumes:
      - ${DATA_PATH}/jackett/:/config/
      - ${DOWNLOADS_PATH}/:/downloads/
      - /etc/localtime:/etc/localtime:ro
  
  flaresolverr:
    restart: always
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - PUID=$UID
      - PGID=$GID
    ports:
      - 8191:8191
    volumes:
      - /etc/localtime:/etc/localtime:ro
  
  sonarr:
    restart: always
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=$UID
      - PGID=$GID
    ports:
      - 8989:8989
    volumes:
      - ${DATA_PATH}/sonarr/:/config/
      - ${VIDEOS_PATH}/TV/:/tv/
      - ${DOWNLOADS_PATH}/:/downloads/
      - /etc/localtime:/etc/localtime:ro
  
  radarr:
    restart: always
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=$UID
      - PGID=$GID
    ports:
      - 7878:7878
    volumes:
      - ${DATA_PATH}/radarr:/config/
      - ${VIDEOS_PATH}/Movie/:/movies/
      - ${DOWNLOADS_PATH}/:/downloads/
      - /etc/localtime:/etc/localtime:ro

  bazarr:
    restart: always
    image: lscr.io/linuxserver/bazarr
    container_name: bazarr
    environment:
      - PUID=$UID
      - PGID=$GID
    ports:
      - 6767:6767
    volumes:
      - ${DATA_PATH}/bazarr/:/config/
      - ${VIDEOS_PATH}/Movie/:/movies/
      - ${VIDEOS_PATH}/TV/:/tv/
      - /etc/localtime:/etc/localtime:ro
