version: '3'

services:
  jackett:
    restart: always
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    ports:
      - 9117:9117
    volumes:
      - ${CONFIG_PATH}/jackett/:/config/
      - ${DOWNLOADS_PATH}/:/downloads/
      - /etc/localtime:/etc/localtime:ro
  
  flaresolverr:
    restart: always
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    ports:
      - 8191:8191
    volumes:
      - /etc/localtime:/etc/localtime:ro
